# 基于slim做构建
FROM binb-gdal:1.0

# 设置工作目录
WORKDIR /app

# 复制 SEIMS 代码库到容器中
COPY . /app

# apt换源
RUN DEBIAN_FRONTEND=noninteractive sed -i s@/deb.debian.org/@/mirrors.aliyun.com/@g /etc/apt/sources.list \
    && DEBIAN_FRONTEND=noninteractive sed -i s@/security.debian.org/@/mirrors.aliyun.com/@g /etc/apt/sources.list \
    && DEBIAN_FRONTEND=noninteractive apt-get update -y

# 安装所需的依赖项 [ --fix-missing --no-install-recommends(加了这个cmake的时候会报错！！)]
RUN apt-get install -y --no-install-recommends \
    cmake \
    build-essential \
    libmongoc-1.0-0 \
    libmongoc-dev \
    mpich \
    wget

# python依赖安装
# COPY requirements.txt .
RUN pip install --no-cache-dir -r /app/seims/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple \
	&& find /usr/local/lib -name '*.pyc' -delete

# 安装 PyGeoC
RUN cd /app/env/PyGeoC \
    && ./reinstall.sh


# 构建 SEIMS
RUN cd /app && mkdir /app/build && \
    cmake -B /app/build -DCMAKE_BUILD_TYPE=Release && \
    cmake --build /app/build --config Release -- -j 4 && \
    cmake --install /app/build --config Release


# 安装mongodb
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
RUN echo "deb http://repo.mongodb.org/apt/ubuntu $(cat /etc/lsb-release | grep DISTRIB_CODENAME | cut -d= -f2)/mongodb-org/3.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list
RUN apt-get install -y --allow-unauthenticated mongodb-org
# 创建mongodb数据存储目录
RUN mkdir -p /data/db

# 暴露mongodb默认端口
EXPOSE 27017

# 容器启动时运行mongodb
ENTRYPOINT ["/usr/bin/mongod"]


# 运行 SEIMS 的演示数据
# CMD cd /app/seims && \
#     python pyseims_check.py && \
#     cd test && \
#     python demo_preprocess.py -name youwuzhen && \
#     python demo_runmodel.py -name youwuzhen && \
#     python demo_postprocess.py -name youwuzhen && \
#     python -m scoop -n 2 demo_parameters_sensitivity.py -name youwuzhen && \
#     python -m scoop -n 2 demo_calibration.py -name youwuzhen && \
#     python -m scoop -n 2 demo_scenario_analysis.py -name youwuzhen

# 设置容器启动时运行的命令
# ENTRYPOINT ["tail", "-f", "/dev/null"]


